# NumPy Giriş

In [2]:
a=[1,2,3,4,5]
b=[3,4,5,4,7]
ab=[]
for i in range(0,len(b)):
    ab.append(a[i]*b[i])
ab

[3, 8, 15, 16, 35]

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))
b=np.array([2,3,4,5,6])
a*b


<class 'numpy.ndarray'>


array([ 2,  6, 12, 20, 30])

In [4]:
x=9

In [5]:
who

a	 ab	 b	 i	 np	 x	 


In [6]:
x

9

# NumPy Arrayleri Oluşturma

## Listelerden Array Oluşturma

In [7]:
import numpy as np

a=np.array([12,33,4,5])
print(a)
type(a)

[12 33  4  5]


numpy.ndarray

In [8]:
np.array([3.14,4,6,1,2])

array([3.14, 4.  , 6.  , 1.  , 2.  ])

In [9]:
np.array([3.14,4,6,1,2],dtype='float32')

array([3.14, 4.  , 6.  , 1.  , 2.  ], dtype=float32)

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [16]:
np.random.normal(0,1, (3,4))

array([[-1.47664421, -0.14867327,  3.0869057 , -1.49616131],
       [-0.03261687,  0.12614882, -0.79376606,  1.0508119 ],
       [ 1.22419726,  0.22730676, -0.16014245,  0.81022662]])

In [17]:
np.random.randint(0,10,(2,2))

array([[8, 0],
       [3, 2]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* **ndim** boyut sayisi
* **shape** boyut bilgisi
* **size** toplam eleman sayisi
* **dtype** array veri tipi

In [19]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([4, 6, 9, 2, 4, 4, 4, 8, 1, 4])

In [20]:
a.shape

(10,)

In [21]:
a.size

10

In [22]:
a.dtype

dtype('int32')

In [23]:
a.ndim

1

In [24]:
a=np.random.randint(10,size=(10,5))
a

array([[6, 4, 5, 1, 7],
       [4, 5, 5, 2, 4],
       [0, 7, 5, 1, 7],
       [9, 6, 5, 6, 4],
       [9, 3, 1, 2, 4],
       [2, 8, 0, 4, 0],
       [2, 4, 9, 0, 4],
       [5, 4, 7, 7, 3],
       [4, 8, 7, 0, 4],
       [7, 9, 0, 9, 4]])

In [25]:
a.ndim

2

In [26]:
a.shape

(10, 5)

In [27]:
a.dtype

dtype('int32')

In [28]:
a.size

50

In [29]:
b=np.random.randint(5,size=(5,5,5))
b

array([[[4, 2, 1, 3, 2],
        [4, 3, 4, 2, 1],
        [0, 2, 4, 2, 3],
        [1, 1, 4, 3, 4],
        [4, 0, 4, 0, 2]],

       [[3, 2, 4, 2, 2],
        [4, 0, 0, 0, 3],
        [2, 0, 4, 4, 3],
        [3, 0, 0, 3, 0],
        [3, 1, 3, 3, 3]],

       [[1, 4, 1, 4, 2],
        [3, 3, 4, 0, 4],
        [2, 2, 2, 1, 4],
        [4, 0, 2, 0, 3],
        [1, 2, 0, 4, 0]],

       [[3, 4, 1, 3, 0],
        [0, 1, 4, 1, 3],
        [4, 4, 2, 2, 3],
        [0, 0, 1, 0, 1],
        [4, 2, 4, 2, 2]],

       [[3, 3, 4, 0, 2],
        [4, 2, 1, 0, 0],
        [1, 2, 0, 0, 2],
        [2, 0, 4, 3, 1],
        [3, 1, 2, 2, 0]]])

In [30]:
b.dtype

dtype('int32')

In [31]:
b.size

125

In [32]:
b.ndim

3

In [33]:
b.shape

(5, 5, 5)

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
type(a)

numpy.ndarray

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Array Birleştirme

In [43]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [44]:
x

array([1, 2, 3])

In [45]:
y

array([4, 5, 6])

In [49]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [112]:
z=[1,2,3]
z

[1, 2, 3]

In [111]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [115]:
a=np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [119]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [120]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# farklı boyutlu array

In [50]:
a= np.array([1,2,3])

b= np.array([[9,8,7],
            [6,5,4]])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [53]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [54]:
a

array([1, 2, 3])

In [55]:
b

array([[9, 8, 7],
       [6, 5, 4]])

In [56]:
b=np.array([[99],[99]])

In [57]:
b

array([[99],
       [99]])

In [139]:
a=np.array([[9,8,7],[6,5,4]])

In [140]:
a

array([[9, 8, 7],
       [6, 5, 4]])

In [141]:
b

array([[99],
       [99]])

In [142]:
np.hstack([a,b])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Array ayırma splitting

In [158]:
x=np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [159]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [153]:
a,b,c,d=np.split(x,[3,4,5])

In [154]:
a

array([1, 2, 3])

In [155]:
b

array([99])

In [156]:
c

array([99])

In [157]:
d

array([3, 2, 1])

In [160]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [177]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [178]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [179]:
ust,alt=np.vsplit(m,[2])

In [180]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [181]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [182]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [183]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [185]:
sol,sag=np.hsplit(m,[2])

In [186]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [187]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama

In [188]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [189]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [190]:
v

array([2, 1, 4, 3, 5])

In [196]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [198]:
v=np.array([2,1,4,3,5])

In [199]:
np.sort(v)

array([1, 2, 3, 4, 5])

### hangi argüman hangi index'e gitti

In [200]:
i=np.argsort(v)
i

array([1, 0, 3, 2, 4], dtype=int64)

In [201]:
v

array([2, 1, 4, 3, 5])

In [202]:
v[i]

array([1, 2, 3, 4, 5])

## NumPy Eleman İşlemleri

In [1]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([5, 1, 4, 1, 6, 4, 7, 5, 9, 5])

In [3]:
a[0]

5

In [4]:
a[-1]

5

In [5]:
a[-2]

9

In [58]:
a[0]=1

In [7]:
a

array([1, 1, 4, 1, 6, 4, 7, 5, 9, 5])

In [10]:
a=np.random.randint(10,size=(3,5))
a

array([[1, 4, 6, 2, 2],
       [9, 5, 4, 4, 0],
       [0, 1, 9, 1, 5]])

In [11]:
a[0][0]

1

In [12]:
a[1][1]

5

In [13]:
a[0,0]=1

In [14]:
a[0][0]

1

In [20]:
a[0][0]=2

In [16]:
a[0][0]

2

In [17]:
a[0,0]

2

In [18]:
a[0,0]=2.2

In [19]:
a[0,0]

2

## Slicing ile Array Alt Kümelerine Erişmek

In [61]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
a[0:3]

array([20, 21, 22])

In [63]:
a[:3]

array([20, 21, 22])

In [24]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [25]:
a[::2]

array([20, 22, 24, 26, 28])

In [26]:
a[1::2]

array([21, 23, 25, 27, 29])

In [27]:
a[2::2]

array([22, 24, 26, 28])

In [28]:
a[1::3]

array([21, 24, 27])

In [67]:
a=np.random.randint(10,size=(5,5))
a

array([[8, 6, 9, 6, 2],
       [9, 6, 3, 2, 3],
       [9, 5, 6, 9, 2],
       [7, 6, 8, 4, 5],
       [5, 1, 2, 5, 7]])

In [68]:
a[:,0]

array([8, 9, 9, 7, 5])

In [69]:
a[:,1]

array([6, 6, 5, 6, 1])

In [70]:
a[:,4]

array([2, 3, 2, 5, 7])

In [74]:
a[1,:]

array([9, 6, 3, 2, 3])

In [75]:
a[1:3,:]

array([[9, 6, 3, 2, 3],
       [9, 5, 6, 9, 2]])

In [76]:
a[2:3,1:3]

array([[5, 6]])

## Array alt kümelerini bağımsızlaştırmak

In [47]:
a=np.random.randint(10,size=(5,5))
a

array([[9, 9, 7, 6, 7],
       [7, 6, 6, 2, 4],
       [7, 0, 8, 2, 9],
       [8, 7, 4, 8, 6],
       [5, 8, 7, 1, 9]])

In [49]:
alt_a=a[0:3,0:2]
alt_a

array([[9, 9],
       [7, 6],
       [7, 0]])

In [50]:
alt_a[0,0]=9999
alt_a[1,1]=9999

In [51]:
alt_a

array([[9999,    9],
       [   7, 9999],
       [   7,    0]])

In [52]:
a

array([[9999,    9,    7,    6,    7],
       [   7, 9999,    6,    2,    4],
       [   7,    0,    8,    2,    9],
       [   8,    7,    4,    8,    6],
       [   5,    8,    7,    1,    9]])

In [54]:
b=np.random.randint(10,size=(5,5))
b

array([[8, 7, 0, 1, 8],
       [8, 9, 0, 6, 0],
       [1, 0, 8, 7, 4],
       [6, 6, 8, 2, 7],
       [5, 6, 2, 1, 5]])

In [56]:
alt_b=b[0:3,0:2].copy()
alt_b

array([[8, 7],
       [8, 9],
       [1, 0]])

In [58]:
alt_b[0,0]=9999
alt_b[1,1]=9999
b

array([[8, 7, 0, 1, 8],
       [8, 9, 0, 6, 0],
       [1, 0, 8, 7, 4],
       [6, 6, 8, 2, 7],
       [5, 6, 2, 1, 5]])

## Fancy Index ile Eleman İşlemleri

In [60]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [64]:
al_getir=[1,2,3]

In [65]:
v[al_getir]

array([3, 6, 9])

In [77]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [84]:
m[satir,sutun]

array([1, 5])

In [80]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
m[0,[1,2]]

array([1, 2])

In [82]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [72]:
v=np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
index=np.array([0,1,2])
index

array([0, 1, 2])

In [77]:
v[index]=99
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [79]:
v[[0,1]]=[4,6]
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])

## Koşullu Eleman İşlemleri

In [81]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [82]:
v>3

array([False, False, False,  True,  True])

In [83]:
v<3

array([ True,  True, False, False, False])

In [84]:
v==3

array([False, False,  True, False, False])

In [86]:
v<=3

array([ True,  True,  True, False, False])

In [85]:
v!=3

array([ True,  True, False,  True,  True])

In [87]:
(2 * v)

array([ 2,  4,  6,  8, 10])

In [88]:
(v ** 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [89]:
(2 * v)==(v**2)

array([False,  True, False, False, False])

# ufunc

np.equal
np.not_equal
np.less
np.less_equal
np.greater
np.greate_equal

In [92]:
v = np.array([1,2,3,4,5])

In [93]:
np.equal(3,v)

array([False, False,  True, False, False])

In [94]:
np.not_equal(2,v)

array([ True, False,  True,  True,  True])

In [95]:
np.less(4,v)

array([False, False, False, False,  True])

In [96]:
np.equal([0,1,3],np.arange(3))

array([ True,  True, False])

In [97]:
np.equal([0,1,3],np.arange(3))

array([ True,  True, False])

In [98]:
np.arange(3)

array([0, 1, 2])

In [100]:
v=np.random.randint(0,10,(3,3))
v

array([[6, 2, 7],
       [9, 5, 8],
       [4, 0, 5]])

In [101]:
v>5

array([[ True, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [102]:
np.sum(v>5)

4

In [104]:
np.sum((v>3) & (v<7))

4

In [105]:
(v>3)&(v<7)

array([[ True, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [106]:
np.sum((v>3)| (v<7))

9

In [107]:
np.sum(v>4,axis=1)

array([2, 3, 1])

In [108]:
np.sum(v>4,axis=0)

array([2, 1, 3])

In [109]:
np.all(v>4)

False

In [111]:
np.all(v>0)

False

In [112]:
np.any(v>4)

True

In [113]:
np.any(v>4,axis=0) 

array([ True,  True,  True])

In [114]:
np.any(v>4,axis=1)

array([ True,  True,  True])

In [117]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [118]:
v[0]

1

In [119]:
v>3

array([False, False, False,  True,  True])

In [120]:
v[v>3]

array([4, 5])

In [122]:
v[(v>1)&(v<5)]

array([2, 3, 4])

## NumPy Hesaplamalı İşlemler

In [85]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [87]:
a-1

array([-1,  0,  1,  2,  3])

In [88]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [89]:
a*5

array([ 0,  5, 10, 15, 20])

In [90]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [91]:
a%2

array([0, 1, 0, 1, 0], dtype=int32)

In [92]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [93]:
a

array([0, 1, 2, 3, 4])

In [95]:
np.add(a,2)

array([2, 3, 4, 5, 6])

In [96]:
np.subtract(a,1)

array([-1,  0,  1,  2,  3])

In [99]:
np.multiply(a,3)

array([ 0,  3,  6,  9, 12])

In [100]:
np.divide(a,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [101]:
np.power(a,3)

array([ 0,  1,  8, 27, 64], dtype=int32)

In [102]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [103]:
np.add.reduce(a)

15

In [104]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [105]:
a=np.random.normal(0,1,30)
a

array([-0.6081101 , -0.07983914,  1.13482486, -1.30047293, -0.49387262,
       -0.16830124,  1.52665505, -0.01845985,  0.87362561,  1.18032275,
       -0.39195823, -0.51263843,  0.42795862,  2.1981724 ,  0.0992635 ,
        1.27705733, -0.23370501,  1.52331693, -0.09367942,  0.19613805,
       -0.84576527, -0.13109471,  2.24259946,  0.46530387,  0.24443092,
        1.65125925, -0.27825741,  1.2477699 , -0.68068128,  0.90693215])

In [106]:
np.mean(a)

0.37862650032937595

In [107]:
np.std(a)

0.9127546091229802

In [108]:
np.var(a)

0.8331209764752445

In [109]:
np.median(a)

0.14770077439553378

In [110]:
sum(a)

11.358795009881279

### eksik değerlere(nA) duyarlı işlemler

In [111]:
np.nanmean(a)
np.nanstd(a)
np.nanvar(a)
np.nanargmin(a)
np.nanargmax(a)
np.nanmedian(a)
a

array([-0.6081101 , -0.07983914,  1.13482486, -1.30047293, -0.49387262,
       -0.16830124,  1.52665505, -0.01845985,  0.87362561,  1.18032275,
       -0.39195823, -0.51263843,  0.42795862,  2.1981724 ,  0.0992635 ,
        1.27705733, -0.23370501,  1.52331693, -0.09367942,  0.19613805,
       -0.84576527, -0.13109471,  2.24259946,  0.46530387,  0.24443092,
        1.65125925, -0.27825741,  1.2477699 , -0.68068128,  0.90693215])

In [113]:
np.min(a)

-1.300472927617325

In [114]:
np.max(a)

2.242599462326235

## Çok boyutlu Array'lerde mat işlemler

In [115]:
a=np.random.normal(0,1,(3,3))
a

array([[ 1.35575925,  1.13642208,  1.07070274],
       [ 1.26698359,  0.51156334,  0.34379047],
       [-2.28686775, -0.13521579, -0.8826079 ]])

In [116]:
a.sum()

2.3805300410663586

In [118]:
a.sum(axis=0)

array([0.33587509, 1.51276963, 0.53188531])

In [119]:
a.sum(axis=1)

array([ 3.56288408,  2.12233741, -3.30469144])

## Farklı Boyutlu Arrayler ile Birlikte Çalışmak(broadcasting)

In [120]:
import numpy as np

In [121]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a+b

array([2, 4, 6])

In [122]:
m=np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [124]:
a

array([1, 2, 3])

In [123]:
a+m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [125]:
a=np.arange(3)
a

array([0, 1, 2])

In [126]:
b=np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [127]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [128]:
M=np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
a=np.arange(3)
a

array([0, 1, 2])

In [130]:
a+M

array([[1., 2., 3.],
       [1., 2., 3.]])

In [131]:
a=np.arange(3).reshape(3,1)
a

array([[0],
       [1],
       [2]])

In [132]:
b=np.arange(3)
b

array([0, 1, 2])

In [133]:
a.shape

(3, 1)

In [134]:
b.shape

(3,)

In [135]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [136]:
m=np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [137]:
a=np.arange(3)
a

array([0, 1, 2])

In [138]:
m.shape

(3, 2)

In [139]:
a.shape

(3,)

In [143]:
try:
    a+m
except:
    print('hatali broadcasting')

hatali broadcasting


## Numpy Yapısal Arrayler (hello!goodbye!numPy!)

In [145]:
isim=['ali','veli','isik']
yas=[25,22,19]
boy=[168,159,172]

In [146]:
data=np.zeros(3,dtype={'names':('isim','yas','boy'),
                      'formats':('U10','i4','f8')})

In [147]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [148]:
data['isim']=isim
data['yas']=yas
data['boy']=boy

In [149]:
data

array([('ali', 25, 168.), ('veli', 22, 159.), ('isik', 19, 172.)],
      dtype=[('isim', '<U10'), ('yas', '<i4'), ('boy', '<f8')])

In [150]:
data['isim']

array(['ali', 'veli', 'isik'], dtype='<U10')

In [151]:
data[0]

('ali', 25, 168.)

In [152]:
data[data['yas']<25]['isim']

array(['veli', 'isik'], dtype='<U10')